import { StyleSheet} from "react-native";
import { Colors } from "react-native/Libraries/NewAppScreen";

export const styles = StyleSheet.create({
    card: {
        width: 'auto',
        margin: 16,
        paddingTop: 16,
        paddingBottom: 16,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    cardContent: {
        width: 'auto',
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        margin: 2,
    },
    cardActions: {
        width: 'auto',
        margin: 2,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardTarefa: {
        width: 'auto',
        margin: 16,
        paddingTop: 16,
        paddingBottom: 16,
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        flexDirection: 'row',
    },
    cardContentTarefa: {
        width: '100%',
        margin: 4,
    },
    cardActionsTarefa: {
        width: '97%',
        margin: 4,
    },
    title: {
        fontSize: 24,
        lineHeight: 28,
        color: '#000000',
        fontWeight: '700',
        paddingTop: 8,
        paddingBottom: 8,
    },
    text: {
        fontSize: 20,
        lineHeight: 28,
        color: '#000000',
        paddingTop: 8,
        paddingBottom: 8,
    },
    tarefaNaoIniciada: {
        fontSize: 20,
        lineHeight: 28,
        color: '#b91c1c',
        fontWeight: '700',
        paddingTop: 8,
        paddingBottom: 8,
    },
    tarefaEmAndamento: {
        fontSize: 20,
        lineHeight: 28,
        color: '#1d4ed8',
        fontWeight: '700',
        paddingTop: 8,
        paddingBottom: 8,
    },
    labelButton: {
        fontSize: 20,
        paddingTop: 2,
        paddingBottom: 2,
    },
    inputContainer: {
        padding: 16,
    },
    input: {
        backgroundColor: Colors.PurpleLight,
        fontSize: 20,
        lineHeight: 28,
        color: '#000000',
        marginTop: 8,
        marginBottom: 8,
    },
    switchContainer: {
        width: '100%',
        margin: 8,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        gap: 8,
    },
    buttonContainer: {
        width: '100%',
        margin: 8,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    button: {
        fontSize: 18,
        padding: 2,
    },
    dateSelectInput: {
        backgroundColor: Colors.PurpleLight,
        borderRadius: 24,
        borderWidth: 1,
        fontSize: 20,
        lineHeight: 28,
        marginTop: 8,
        marginBottom: 8,
    },
});